## Introducing Numpy

In [24]:
# we can run cells with ctrl-enter or shift-enter
a=2
b=7
a/b

0.2857142857142857

In [21]:
b=99
a=33
b/a

3.0

In [26]:
b**a
def fn(n,m):
    return n*2+m*2
fn(a,b)

18

In [27]:
# import the required libraries for Data Analysis
import numpy as np # convention
import pandas as pd
import matplotlib.pyplot as plt

* Numeric Python is a library for managing large data sets

In [33]:
# numpy provides additional data structures
# array range. start, stop-before, step
n = np.arange(3.0, 12.5, 0.5) # only one data type permitted at a time
n
# n.dtype

array([ 3. ,  3.5,  4. ,  4.5,  5. ,  5.5,  6. ,  6.5,  7. ,  7.5,  8. ,
        8.5,  9. ,  9.5, 10. , 10.5, 11. , 11.5, 12. ])

In [36]:
# Numpy also offers an array structure
#                 (rows, columns)
d = np.random.randn(2, 3) # we have an array 
d.dtype
d.shape

(2, 3)

In [43]:
# there is no (practical) limit to the array size or dimensions
e = np.random.randn(9,5)
e # we havea 2-d array
f = np.random.randn(5,6,3) # we can have multi-dimensional arrays
f.shape

(5, 6, 3)

In [58]:
# creating arrays
g = np.empty( (4,4) ) # create an in-memory array
g = np.zeros( (4,4) ) # ...also set to zero
g.dtype
g

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [65]:
s = d.astype(np.str_) # this is numpy syntax
s
s.dtype

dtype('<U32')

In [71]:
i = f.astype(np.int32) # typically we use int32 or int64
i.T # transform (switch rows with columns)

array([[[-2,  0,  1,  0,  1],
        [ 0,  0,  1,  0, -1],
        [ 0,  2,  0, -1,  1],
        [ 0,  0, -1,  0,  0],
        [-1,  0,  1,  0,  0],
        [-1,  1,  0,  0,  0]],

       [[ 0,  0,  0,  0,  0],
        [ 0,  1,  0,  0,  0],
        [ 0,  0, -1,  0,  0],
        [ 1,  0,  0, -1,  1],
        [ 0,  2,  0,  0,  0],
        [ 0,  0,  0, -2,  0]],

       [[ 1,  0,  1, -1,  1],
        [ 0,  0,  0, -2, -1],
        [ 0,  0,  0,  1,  0],
        [ 0, -1, -2,  0,  1],
        [ 0,  0,  0, -1,  0],
        [ 1,  0, -1, -1, -1]]])

### Calculations with Arrays

In [80]:
x = np.random.randn(3,3,3)
z = np.zeros((3,3,3))

In [93]:
z+3 # most operations do NOT alter the orignal structure
# generaly complex calculations on collections of values are MUCH faster in Numpy than Python
abs((z+3)/(x*2)) # numpy calculations are VERY performant

array([[[  1.24130184,   1.81193161,   3.03897297],
        [  9.46425742,   2.98947475,   1.96498897],
        [ 13.98807297,   2.40916705, 545.86397698]],

       [[ 16.54158823,  60.30794564,   1.5103972 ],
        [  1.33003142,  14.73894902,   2.31771987],
        [  1.42163696,   1.04301179,   1.7949359 ]],

       [[  3.44085995,  16.95434915,   4.87356068],
        [  1.37757347,   2.28580248,   2.61881735],
        [  3.45891602,   5.3437246 ,   2.40783378]]])

### Accessing Members of Arrays

In [98]:
d

array([[ 0.72645685,  0.31342091, -1.60187963],
       [ 0.50862746, -1.13172095, -2.1756225 ]])

In [112]:
d[1][1] # the item at 1,1
d[0:1] # slicing is start:stop-before:step
e[1:4:2] # [1:3]

array([[ 0.73934176,  1.25732058, -0.05883049, -0.85621263,  0.62987335],
       [ 0.83457172,  1.56035219,  0.32841965,  0.81833634,  0.31981554]])

In [114]:
d[::-1] # we can show reverse

array([[ 0.50862746, -1.13172095, -2.1756225 ],
       [ 0.72645685,  0.31342091, -1.60187963]])

In [116]:
# we can assign values
d[1,1]=0 # this DOES alter the original structure
d[0]=1
d

array([[ 1.        ,  1.        ,  1.        ],
       [ 0.50862746,  0.        , -2.1756225 ]])